# Setup
title:               National Contiguity Force Directed Graph
tagline:             Visualization using D3.js

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          css
  style:            :compressed
